application:
  datasource:
    url: jdbc:mysql://localhost:3306/VetClinicSystem
    username: root
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    logging:
      level:
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace


